import type { Metadata } from "next";
import { JsonLd } from "@/components/JsonLd";
import { MarketingArticle } from "@/components/MarketingArticle";
import { breadcrumbStructuredData } from "@/lib/structured-data";

const TITLE = "Security & data handling";
const DESCRIPTION =
  "How Mintdish stores recipes, photos, and account data; how AI parsing and analytics work; and what is and is not shared with third parties.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: {
    canonical: "/security",
    languages: {
      en: "/security",
      ro: "/security/ro",
      "x-default": "/security",
    },
  },
  openGraph: { title: `${TITLE} — Mintdish`, description: DESCRIPTION },
  twitter: { title: `${TITLE} — Mintdish`, description: DESCRIPTION },
};

export default function Security() {
  return (
    <>
      <JsonLd
        data={breadcrumbStructuredData([
          { name: "Home", url: "/welcome" },
          { name: TITLE, url: "/security" },
        ])}
      />
      <MarketingArticle
        locale="en"
        breadcrumbs={[{ name: "Home", href: "/welcome" }, { name: TITLE }]}
      >
        <h1>Security &amp; data handling</h1>
        <p className="text-lg">
          Mintdish handles recipes you save, photos you upload, and your account
          information. This page summarises how that data is stored, who can see
          it, and how AI parsing and analytics work. The full legal version is
          in our <a href="/privacy">Privacy Policy</a>.
        </p>

        <h2>Where your data lives</h2>
        <ul>
          <li>
            <strong>Recipes &amp; account data</strong> are stored in a Postgres
            database hosted on Neon (EU region) and accessed only over TLS.
          </li>
          <li>
            <strong>Photos and generated hero images</strong> are stored in
            Vercel Blob with private access and served back to you only through
            an authenticated proxy.
          </li>
          <li>
            <strong>Authentication</strong> is handled by NextAuth.js with
            Google OAuth — Mintdish never sees your Google password.
          </li>
        </ul>

        <h2>How AI parsing works</h2>
        <ul>
          <li>
            Recipe URLs, transcripts, and photos are sent to Google Gemini under
            Google&apos;s API terms purely for parsing and chat responses.
          </li>
          <li>
            Mintdish does not train any models of its own and does not share
            your library with third parties beyond what is required to deliver
            the service.
          </li>
          <li>
            Hero images generated by Gemini 2.5 Flash Image are watermarked
            &quot;Generated with AI&quot; so they cannot be confused with real
            photos.
          </li>
        </ul>

        <h2>Analytics &amp; error tracking</h2>
        <ul>
          <li>
            Analytics (Google Analytics, Vercel Analytics, Speed Insights) only
            run if you accept analytics cookies in the consent banner.
          </li>
          <li>
            Sentry is used for error tracking; user IDs and emails may appear in
            error reports to help debug issues.
          </li>
          <li>
            You can update or revoke analytics consent any time from the{" "}
            <a href="/cookies">Cookie preferences</a> page.
          </li>
        </ul>

        <h2>Account deletion</h2>
        <p>
          To delete your account and all associated data — recipes, photos, chat
          history, and waitlist email — email{" "}
          <a href="mailto:horia@mintdish.io">horia@mintdish.io</a> from the
          address linked to your account and we will action it within seven
          days.
        </p>

        <h2>Reporting a vulnerability</h2>
        <p>
          If you believe you have found a security issue in Mintdish, please
          email <a href="mailto:horia@mintdish.io">horia@mintdish.io</a> with
          details and steps to reproduce. We aim to acknowledge reports within
          two business days.
        </p>
      </MarketingArticle>
    </>
  );
}
